"""add category

Revision ID: 6971b267038b
Revises: 4e081b9cb43a
Create Date: 2024-02-15 10:58:48.154732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6971b267038b'
down_revision = '4e081b9cb43a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('availablecars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])

    with op.batch_alter_table('hiredcars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_location', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('destination', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hiredcars', schema=None) as batch_op:
        batch_op.drop_column('destination')
        batch_op.drop_column('pickup_location')

    with op.batch_alter_table('availablecars', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')

    op.drop_table('categories')
    # ### end Alembic commands ###
